### ISSUE TITLE
More independent exercises, group exercises, and integrated assignments

### ISSUE THREAD

**Issue by kcotto** [griffithlab/rnabio.org#15]
- Migrated from rnabio.org proposed improvements page

- Each module should have at least two exercises where the students are not copying/pasting anything. One could be at 1/2 way point, and the other at the end of the module. The one at the end could be a group exercise.
- Each day should end with at least one hour of integrated assignment.

**Comment by malachig** [comment]
We did this up to a point, but they kind of tail off.  The last practical exercise is expression.  It would be good to continue this through to differential expression at least using the practical exercise data. i.e. HCC1395_tumor vs HCC1395_normal

**Comment by obigriffith** [comment]
This has been largely completed
