### ISSUE TITLE
Get X11 support working on AMI

### ISSUE THREAD

**Issue by kcotto** [griffithlab/rnabio.org#17]
Migrated from rnabio.org proposed improvements page

For R and other applications it would be nice if X11 worked. Note the install instructions for R would need to change as well.

**Comment by malachig** [comment]
This is arguably deprecated by better approaches.  RStudio on the AWS instance would work.  Apache Guacamole would also work.

**Comment by kcotto** [comment]
It's fairly easy to run RStudio on AWS now - see here: https://towardsdatascience.com/how-to-run-rstudio-on-aws-in-under-3-minutes-for-free-65f8d0b6ccda. Closing this issue for now.
