### ISSUE TITLE
Create a trimming section

### ISSUE THREAD

**Issue by kcotto** [griffithlab/rnabio.org#18]
Migrated from rnabio.org proposed improvements page

Create a wiki section and exercise that summarizes read trimming concepts. Start with some raw data, including aligned reads. Align these reads without any trimming and assess alignment statistics using Picard, FastQC, etc. Now take these same reads and perform both adaptor trimming and quality trimming. Re-align the trimmed reads and assess the effect of trimming on alignment metrics.

Note: we do have an okay trimming section now, but it should really be starting with raw reads, rather than those that had already been proven to align to chr 22. This makes it harder to see the value of trimming by comparing alignment pre/post trimming. Instead we should perhaps get chr22 matching reads by k-mer analysis (kallisto), then trim (adapter and/or quality), then align trimmed and untrimmed, and summarize the difference.

**Comment by malachig** [comment]
We have a pretty decent trimming section now.
