### ISSUE TITLE
Improve alignment QC section

### ISSUE THREAD

**Issue by kcotto** [griffithlab/rnabio.org#22]
Migrated from rnabio.org proposed improvements page

In particular we should add use of Picard CollectRnaSeqMetrics (https://broadinstitute.github.io/picard/command-line-overview.html) and RNA-SeQC (http://www.broadinstitute.org/cancer/cga/rna-seqc). It would also be good to include use of splicing metrics calculated from the TopHat junctions files. A standalone version of the TGI tool that does this would need to be created for this purpose.

Also use MultiQC to produce a combined report of the QC results: http://multiqc.info/

**Comment by malachig** [comment]
- Pizzly? (As already done in pmbio.org) 
- STAR-fusion?
- FusionCatcher?

Annotate with AGfusion?

**Comment by malachig** [comment]
This is done.
