### ISSUE TITLE
Complete multiQC section

### ISSUE THREAD

**Issue by malachig** [griffithlab/rnabio.org#32]
At the last course at CSHL we got close to have a good example multiQC report to discuss real data issues with the class.  It wasn't quite complete though.

Goal is to have ~5-10 samples representing various scenarios that are QC analyzed but are not small filtered read data sets.

**Comment by malachig** [comment]
Basically polish up the last section `MultiQC on full bam files` here:
https://rnabio.org/module-02-alignment/0002/06/01/Alignment_QC/

* clean up sample names
* create a link to the multiqc report pre-generated

**Comment by kcotto** [comment]
This is now complete at the end of the above-mentioned link. They can download the mutliQC report and then visualize real-life examples.
