### ISSUE TITLE
Low numbers of genes in DGE 

### ISSUE THREAD

**Issue by sekhwal** [griffithlab/rnabio.org#44]
I am trying to perform DGE analysis of Kallisto results. However, the genes in differential gene expression are very low numbers.

Here is my script and results:

names(files) <- paste0("sample", 1:187)
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
head(txi.kallisto$counts)
sampleMetaData <- data.frame(Group=c(rep(c("mutant"), 94), rep(c("control"), 93)), Gender=rep(c(rep(c("F"), 
130), rep(c("M"), 57))))

rownames(sampleMetaData) <- colnames(txi.kallisto$counts)
dds <- DESeqDataSetFromTximport(txi.kallisto, sampleMetaData, design= ~ Group + Gender)
res <- results(dds)
dds <- DESeq(dds)

###Results###
out of 171018 with nonzero total read count
adjusted p-value < 0.1
LFC > 0 (up)       : 975, 0.57%
LFC < 0 (down)     : 12, 0.007%
outliers [1]       : 0, 0%
low counts [2]     : 73970, 43%
(mean count < 2)

**Comment by kcotto** [comment]
It's hard for us to examine this without us having access to the starting data that you are using.
