### ISSUE TITLE
stringtie_expression_matrix.pl

### ISSUE THREAD

**Issue by AstrMary** [griffithlab/rnabio.org#45]
Hi,

thank you for the amazing code ..
I run the below command and it worked !!
./stringtie_expression_matrix.pl --expression_metric=FPKM --result_dirs='RNAseq_Norm_Lane1,RNAseq_Norm_Lane2,RNAseq_Tumor_Lane1,RNAseq_Tumor_Lane2' --transcript_matrix_file=transcript_fpkm_all_samples.tsv --gene_matrix_file=gene_fpkm_all_samples.tsv
However, I am naive at Perl coding  so I was wandering if there is a way to  add an extra column with the gene name at the gene_abundances.tsv  file 

Thanks a lot..

**Comment by malachig** [comment]
This should not be too hard ... You only want it to be added for the gene abundance file?

The gene names are already being parsed, so you would just need to add something like this at line 203:
`$exp{$gene_id}{gene_name} = $gene_name;`

Then you would have to modify the block starting at line 110 to add this information to the output.
